### PR TITLE
Adding my profile to the team website

### PR DESCRIPTION
**Pull request by wizcriz**
Hi Byron, I'm adding my profile pic to the team, please accept my request

### CODE REVIEW

**Comment by bsommardahl** [comment]
@wizcriz Hi! I think you are not supposed to modify they html. Only the PUG file since the HTML is generated at build-time.

**Comment by wizcriz** [comment]
Got it, do I do it again or that's fine?

**Comment by bsommardahl** [comment]
You don't need to do it again, but you do need to revert your change to the index.html file and commit. You should see in this pull-request only two files changed. 1) your image uploaded and 2) the pug file containing your modification.

**Comment by wizcriz** [comment]
Ok got it, done!

**Pull request merged**
